# Things 3 MCP Server Configuration
# Example configuration file showing all available options

# Server Configuration
server_name: "things3-mcp-server"
server_version: "1.0.0"
server_description: "MCP server for Things 3 task management integration"

# AppleScript Execution Configuration
applescript_timeout: 30.0  # Timeout in seconds
applescript_retry_count: 3  # Number of retries
preferred_execution_method: "hybrid"  # url_scheme, applescript, or hybrid

# Cache Configuration
enable_caching: true
cache_max_size: 1000  # Maximum cached items
cache_default_ttl: 300  # Default TTL in seconds
cache_memory_limit: 100  # Memory limit in MB

# Logging Configuration
log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
enable_detailed_logging: false
enable_debug_logging: false
log_file_path: null  # Path to log file (null for stdout)

# Validation Configuration
max_title_length: 500
max_notes_length: 10000
max_tags_per_item: 20
max_checklist_items: 50

# Performance Configuration
max_concurrent_operations: 10
batch_operation_max_size: 100
search_results_limit: 100

# Security Configuration
enable_input_sanitization: true
allowed_hosts:
  - "localhost"
  - "127.0.0.1"

# Feature Flags
enable_experimental_features: false
enable_analytics: true
enable_health_checks: true

# Things 3 Specific Configuration
things_app_name: "Things3"
things_url_scheme_base: "things:///"
verify_things_availability: true

# Tag Management Configuration
# Controls how the server handles unknown tags during operations

# Tag creation policy - determines what happens with unknown tags
# Four policy options available:
#
# 1. "allow_all" (default):
#    - Automatically creates unknown tags up to max_auto_created_tags_per_operation limit
#    - Provides feedback about created tags in response
#    - Best for flexible tag management
#
# 2. "filter_unknown":
#    - Silently removes unknown tags from operations
#    - Operations proceed with only known tags
#    - Best for strict tag control without operation failures
#
# 3. "warn_unknown":
#    - Allows unknown tags but warns they will be auto-created by Things
#    - Provides warnings in response but doesn't create tags proactively
#    - Best for awareness of tag creation without blocking operations
#
# 4. "reject_unknown":
#    - Rejects entire operations if unknown tags are present
#    - Forces explicit tag creation before use
#    - Best for strictest tag control (use with tag_policy_strict_mode: true)
tag_creation_policy: "allow_all"

# Enable strict mode for tag policy enforcement
# When true, policy violations cause operation failures
# When false, policy violations generate warnings but operations continue
tag_policy_strict_mode: false

# Case sensitivity for tag validation
# When true, tags are matched exactly including case
# When false, tag matching is case-insensitive
tag_validation_case_sensitive: false

# Maximum number of tags that can be auto-created in a single operation
# Prevents accidental creation of excessive tags due to typos
max_auto_created_tags_per_operation: 10

# Development Configuration
enable_mock_mode: false
mock_data_path: null